make print compatible with both python2 and python3
Resolves https://github.com/jumanjihouse/pre-commit-hooks/issues/26

    Check file encoding.........................................................Failed
    hookid: require-ascii

    File "/Users/dstull/.cache/pre-commit/repojmex2sqj/py_env-python3.6/bin/require-ascii.py", line 26
    print result.ljust(8) + filename.ljust(50),
    ^
    SyntaxError: invalid syntax